#!/bin/bash
. /usr/local/bin/s6-load-locale-env
export PATH="/nix/var/nix/profiles/default/bin:$PATH"
export HOME=/home/gem
cd /home/gem/projects/CartaClient/design
exec /command/s6-setuidgid gem bun run serve.ts
