[program:project-supervisor]
command=/usr/bin/supervisord -n -c /etc/supervisor/projects.conf
user=root
autostart=true
autorestart=true
priority=100
stdout_logfile=/var/log/supervisor/project-supervisor.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/var/log/supervisor/project-supervisor.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
