[program:dns-update]
command=/usr/local/bin/dns-update.sh
user=root
autostart=true
autorestart=false
startsecs=0
priority=25
stdout_logfile=/var/log/supervisor/dns-update.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stderr_logfile=/var/log/supervisor/dns-update.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1
environment=CLOUDFLARE_API_TOKEN="%(ENV_CLOUDFLARE_API_TOKEN)s",CLOUDFLARE_ZONE_ID="%(ENV_CLOUDFLARE_ZONE_ID)s"
