[program:tailscale]
command=tailscaled --state=/var/lib/tailscale/tailscaled.state
user=root
autostart=true
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/tailscale.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/var/log/supervisor/tailscale.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
