[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/projects-supervisord.log
pidfile=/var/run/projects-supervisord.pid

[supervisorctl]
serverurl=unix:///var/run/projects-supervisor.sock

[unix_http_server]
file=/var/run/projects-supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpc_interface

[include]
files = /etc/supervisor/projects.d/*.conf
