[program:codery-ci-daemon]
command=/opt/codery/codery-ci daemon
user=root
autostart=true
autorestart=true
priority=40
stdout_logfile=/var/log/supervisor/codery-ci-daemon.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/var/log/supervisor/codery-ci-daemon.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
