[program:code-server]
command=code-server --bind-addr 0.0.0.0:7000 --auth none --disable-telemetry
directory=/home/gem/projects
environment=HOME="/home/gem"
autostart=true
autorestart=true
priority=50
stdout_logfile=/tmp/code-server.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stderr_logfile=/tmp/code-server.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1
