[program:opencode]
command=opencode serve --hostname 0.0.0.0 --port 3000 --cors https://opencode.__DOMAIN_NAME__
directory=/home/gem/projects
environment=HOME="/home/gem"
autostart=true
autorestart=true
priority=40
stdout_logfile=/tmp/opencode.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=2
stderr_logfile=/tmp/opencode.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=2
