[program:tmux]
command=bash -c "tmux new-session -d -s main && exec sleep infinity"
user=gem
directory=/home/gem/projects
environment=HOME="/home/gem"
autostart=true
autorestart=true
priority=50
stdout_logfile=/tmp/tmux.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stderr_logfile=/tmp/tmux.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1
