[program:ttyd]
command=ttyd -W -p 7681 tmux attach -t main
user=gem
directory=/home/gem/projects
environment=HOME="/home/gem"
autostart=true
autorestart=true
priority=60
stdout_logfile=/tmp/ttyd.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=1
stderr_logfile=/tmp/ttyd.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=1
